# This workflow creates a GitHub Release after deployment, including the deployed site URL in the release notes.
name: Release with Deployed Site Link

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

jobs:
  create-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=now::$(date +'%Y-%m-%d_%H-%M-%S')"

      - name: Create Release with Deployed Site Link
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.date.outputs.now }}
          name: "Deployed Site Release ${{ steps.date.outputs.now }}"
          body: |
            🚀 The site is live at:
            https://vishwamartur.github.io/wedding-photography-portfolio/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
